name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    full-test:
        container: cuaesd/aesd-autotest:24-assignment7-buildroot
        runs-on: self-hosted
        timeout-minutes: 120
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run: git submodule update --init --recursive
          - name: Create non-root user
            run: |
              useradd -m builduser
              chown -R builduser:builduser $GITHUB_WORKSPACE
          - uses: webfactory/ssh-agent@v0.5.3
            with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          - name: Run full test as a non-root user
            env:
              GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
            run: su builduser -c "./full-test.sh"
          - name: Cleanup
            if: always()
            run: |
              ssh-add -D
