name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    full-test:
        container: cuaesd/aesd-autotest:24-assignment7-buildroot
        runs-on: self-hosted
        timeout-minutes: 120
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run: git submodule update --init --recursive
          - uses: webfactory/ssh-agent@v0.5.3
            with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          - name: Downgrade fakeroot to 1.34
            run: |
              sed -i 's/^FAKEROOT_VERSION = .*/FAKEROOT_VERSION = 1.34/' buildroot/package/fakeroot/fakeroot.mk
              echo "sha256  5727f16d8903792588efa7a9f8ef8ce71f8756e746b62e45162e7735662e56bb fakeroot_1.34.orig.tar.gz" >> buildroot/package/fakeroot/fakeroot.hash
          - name: Run full test
            env:
              FORCE_UNSAFE_CONFIGURE: 1
              GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
            run: ./full-test.sh
          - name: Cleanup
            if: always()
            run: |
              ssh-add -D
